import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { adminApi, adminToken } from "@/lib/api"

export function LoginPage({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [token, setToken] = useState("")
  const [error, setError] = useState("")
  const [busy, setBusy] = useState(false)

  async function submit(event: React.FormEvent) {
    event.preventDefault()
    setBusy(true)
    adminToken.set(token.trim())
    try {
      await adminApi.health()
      setError("")
      onAuthenticated()
    } catch {
      adminToken.clear()
      setError("Invalid admin token")
    } finally { setBusy(false) }
  }

  return <main className="flex min-h-screen items-center justify-center bg-muted/30 p-6"><Card className="w-full max-w-md"><CardHeader><CardTitle>ChatGPT MCP</CardTitle><CardDescription>Enter the admin token generated by the CLI.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}><div className="space-y-2"><Label htmlFor="admin-token">Admin token</Label><Input id="admin-token" type="password" autoComplete="current-password" value={token} onChange={(event) => setToken(event.target.value)} /></div>{error ? <div className="text-sm text-destructive">{error}</div> : null}<Button className="w-full" disabled={busy || !token.trim()} type="submit">Sign in</Button></form></CardContent></Card></main>
}
