import { useEffect, useState, type ReactNode } from "react"
import { Network, RefreshCw } from "lucide-react"
import { CopyButton } from "@/components/copy-button"
import { DetailRow } from "@/components/detail-row"
import { PageError } from "@/components/page-state"
import { PageHeader } from "@/components/page-header"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { ButtonGroup } from "@/components/ui/button-group"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Spinner } from "@/components/ui/spinner"
import { Switch } from "@/components/ui/switch"
import { adminApi, type TunnelAdminKeyRequest, type TunnelAdminKeyStatus, type TunnelAdminScope, type TunnelConfig, type TunnelStatus } from "@/lib/api"

const emptyConfig: TunnelConfig = { enabled: false }
type AdminScopeKind = "organization" | "workspace" | "tenant"

export function TunnelPage() {
  const [config, setConfig] = useState<TunnelConfig>(emptyConfig)
  const [status, setStatus] = useState<TunnelStatus | null>(null)
  const [adminConfigured, setAdminConfigured] = useState(false)
  const [adminKey, setAdminKey] = useState("")
  const [adminScope, setAdminScope] = useState<AdminScopeKind>("workspace")
  const [adminScopeID, setAdminScopeID] = useState("")
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)
  const [adminBusy, setAdminBusy] = useState(false)
  const [refreshing, setRefreshing] = useState(false)
  const [message, setMessage] = useState("")
  const [error, setError] = useState("")

  useEffect(() => {
    let active = true
    void Promise.all([adminApi.tunnelConfig(), adminApi.tunnel(), adminApi.tunnelAdminKey()]).then(([nextConfig, nextStatus, nextAdmin]) => { if (active) { setConfig(nextConfig); setStatus(nextStatus); applyAdminStatus(nextAdmin, setAdminConfigured, setAdminScope, setAdminScopeID); setError(""); setLoading(false) } }).catch((value) => { if (active) { setError(errorText(value)); setLoading(false) } })
    const timer = window.setInterval(() => { void adminApi.tunnel().then((next) => { if (active) setStatus(next) }).catch(() => undefined) }, 3000)
    return () => { active = false; window.clearInterval(timer) }
  }, [])

  async function refresh() { setRefreshing(true); try { const [nextStatus, nextAdmin] = await Promise.all([adminApi.tunnel(), adminApi.tunnelAdminKey()]); setStatus(nextStatus); applyAdminStatus(nextAdmin, setAdminConfigured, setAdminScope, setAdminScopeID); setError("") } catch (value) { setError(errorText(value)) } finally { setRefreshing(false) } }
  async function saveRuntime() { setBusy(true); try { setStatus(await adminApi.configureTunnel(runtimeConfig(config))); setConfig({ ...config, api_key: "", runtime_key_configured: Boolean(config.api_key || config.runtime_key_configured) }); setMessage("Runtime tunnel configuration saved."); setError("") } catch (value) { setError(errorText(value)); setMessage("") } finally { setBusy(false) } }
  async function toggle() { const active = status?.running || status?.restarting; setBusy(true); try { setStatus(active ? await adminApi.stopTunnel() : await adminApi.startTunnel()); setMessage(active ? "Tunnel stopped." : "Tunnel start requested."); setError("") } catch (value) { setError(errorText(value)); setMessage("") } finally { setBusy(false) } }
  async function saveAdmin() { if (!adminScopeID.trim()) { setError("Admin scope ID is required."); return } setAdminBusy(true); try { const next = await adminApi.configureTunnelAdminKey(adminRequest(adminKey, adminScope, adminScopeID)); setAdminKey(""); applyAdminStatus(next, setAdminConfigured, setAdminScope, setAdminScopeID); setStatus(await adminApi.tunnel()); setMessage(adminResultMessage("Admin key verified and saved", next)); setError("") } catch (value) { setError(errorText(value)); setMessage("") } finally { setAdminBusy(false) } }
  async function verifyAdmin() { setAdminBusy(true); try { const next = await adminApi.verifyTunnelAdminKey(); applyAdminStatus(next, setAdminConfigured, setAdminScope, setAdminScopeID); setMessage(adminResultMessage("Admin key verified", next)); setError("") } catch (value) { setError(errorText(value)); setMessage("") } finally { setAdminBusy(false) } }
  async function removeAdmin() { setAdminBusy(true); try { const next = await adminApi.removeTunnelAdminKey(); setAdminKey(""); applyAdminStatus(next, setAdminConfigured, setAdminScope, setAdminScopeID); setStatus(await adminApi.tunnel()); setMessage("Admin key removed."); setError("") } catch (value) { setError(errorText(value)); setMessage("") } finally { setAdminBusy(false) } }

  const active = status?.running || status?.restarting
  const state = status?.restarting ? "Reconnecting" : status?.running ? status.ready ? "Ready" : "Connecting" : "Stopped"
  const variant = status?.ready ? "default" : active ? "secondary" : "outline"
  return <div className="space-y-6"><PageHeader title="Tunnel" description="Configure runtime connectivity and OpenAI Tunnel administration separately." actions={<Button aria-label="Refresh tunnel status" disabled={refreshing} size="sm" variant="outline" onClick={() => void refresh()}><RefreshCw className={refreshing ? "animate-spin" : ""} />Refresh</Button>} /><PageError message={error} />{message ? <Alert><Network /><AlertDescription>{message}</AlertDescription></Alert> : null}<div className="grid gap-6 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><TunnelStatusCard active={active} busy={busy} config={config} loading={loading} state={state} status={status} variant={variant} onToggle={() => void toggle()} /><div className="space-y-6"><RuntimeCard busy={busy} config={config} loading={loading} setConfig={setConfig} onSave={() => void saveRuntime()} /><AdminCard busy={adminBusy} configured={adminConfigured} keyValue={adminKey} scope={adminScope} scopeID={adminScopeID} setKey={setAdminKey} setScope={(value) => { setAdminScope(value); setAdminScopeID("") }} setScopeID={setAdminScopeID} onSave={() => void saveAdmin()} onVerify={() => void verifyAdmin()} onRemove={() => void removeAdmin()} /></div></div></div>
}

function RuntimeCard({ busy, config, loading, setConfig, onSave }: { busy: boolean; config: TunnelConfig; loading: boolean; setConfig: (value: TunnelConfig) => void; onSave: () => void }) { return <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>Runtime configuration</CardTitle><CardDescription className="mt-1">Read + Use credential and startup settings used by the running cgm tunnel client.</CardDescription></div><Badge variant={config.runtime_key_configured ? "secondary" : "outline"}>{config.runtime_key_configured ? "Key configured" : "No runtime key"}</Badge></div></CardHeader><CardContent><FieldGroup><Field orientation="horizontal"><div className="min-w-0 flex-1"><FieldLabel>Start automatically</FieldLabel><FieldDescription>Connect to the OpenAI Tunnel control plane when the runtime starts.</FieldDescription></div><Switch checked={config.enabled} disabled={loading} onCheckedChange={(enabled) => setConfig({ ...config, enabled })} /></Field><div className="grid gap-5 md:grid-cols-2"><ConfigField label="Tunnel ID" description="Assigned OpenAI tunnel identifier."><Input placeholder="tunnel_..." value={config.id ?? ""} onChange={(event) => setConfig({ ...config, id: event.target.value })} /></ConfigField><ConfigField label="Runtime key" description={config.runtime_key_configured ? "Leave blank to keep the current stored Read + Use key." : "OpenAI tunnel runtime key with Read + Use permissions."}><Input autoComplete="off" placeholder={config.runtime_key_configured ? "Leave blank to keep current key" : "Runtime API key"} type="password" value={config.api_key ?? ""} onChange={(event) => setConfig({ ...config, api_key: event.target.value })} /></ConfigField><ConfigField label="Control plane base URL" description="Usually left empty for the OpenAI default."><Input placeholder="https://api.openai.com" value={config.control_plane_base_url ?? ""} onChange={(event) => setConfig({ ...config, control_plane_base_url: event.target.value })} /></ConfigField><ConfigField label="Organization ID" description="Optional runtime organization scope."><Input placeholder="org_..." value={config.organization_id ?? ""} onChange={(event) => setConfig({ ...config, organization_id: event.target.value })} /></ConfigField></div></FieldGroup></CardContent><CardFooter className="justify-end border-t"><Button disabled={busy || loading} onClick={onSave}>{busy ? "Saving..." : "Save runtime"}</Button></CardFooter></Card> }
function AdminCard({ busy, configured, keyValue, scope, scopeID, setKey, setScope, setScopeID, onSave, onVerify, onRemove }: { busy: boolean; configured: boolean; keyValue: string; scope: AdminScopeKind; scopeID: string; setKey: (value: string) => void; setScope: (value: AdminScopeKind) => void; setScopeID: (value: string) => void; onSave: () => void; onVerify: () => void; onRemove: () => void }) { return <Card><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>Admin management</CardTitle><CardDescription className="mt-1">Tunnels Manage credential used only for management API operations. It is never reused as the runtime key.</CardDescription></div><Badge variant={configured ? "secondary" : "outline"}>{configured ? "Configured" : "Not configured"}</Badge></div></CardHeader><CardContent><FieldGroup><ConfigField label="Admin key" description={configured ? "Leave blank to keep the stored admin key; Save & verify can update its scope." : "Admin API key with Tunnels Manage permission. It is stored only after verification succeeds."}><Input autoComplete="off" placeholder={configured ? "Leave blank to keep current key" : "Admin API key"} type="password" value={keyValue} onChange={(event) => setKey(event.target.value)} /></ConfigField><div className="grid gap-5 md:grid-cols-2"><ConfigField label="Scope type" description="Verification and management use exactly one scope."><Select value={scope} onValueChange={(value) => setScope(value as AdminScopeKind)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="organization">Organization</SelectItem><SelectItem value="workspace">Workspace</SelectItem><SelectItem value="tenant">Tenant</SelectItem></SelectContent></Select></ConfigField><ConfigField label={`${scopeLabel(scope)} ID`} description={`OpenAI ${scope} used to verify Tunnels Manage access.`}><Input placeholder={scopePlaceholder(scope)} value={scopeID} onChange={(event) => setScopeID(event.target.value)} /></ConfigField></div></FieldGroup></CardContent><CardFooter className="justify-between gap-3 border-t"><div className="text-xs text-muted-foreground">Admin credentials are stored in the OS keyring; tunnel.&lt;ext&gt; keeps only scope and configured-state metadata.</div><ButtonGroup>{configured ? <><Button disabled={busy} variant="outline" onClick={onVerify}>Verify</Button><Button disabled={busy} variant="outline" onClick={onRemove}>Remove</Button></> : null}<Button disabled={busy || !scopeID.trim()} onClick={onSave}>{busy ? "Verifying..." : "Save & verify"}</Button></ButtonGroup></CardFooter></Card> }
function TunnelStatusCard({ active, busy, config, loading, state, status, variant, onToggle }: { active: boolean | undefined; busy: boolean; config: TunnelConfig; loading: boolean; state: string; status: TunnelStatus | null; variant: "default" | "secondary" | "outline"; onToggle: () => void }) { return <Card className="h-fit"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{status?.metadata?.name || "OpenAI Secure MCP Tunnel"}</CardTitle><CardDescription className="mt-1">{status?.metadata?.description || "Current control-plane connection and runtime state."}</CardDescription></div><Badge variant={variant}>{status?.restarting || (status?.running && !status.ready) ? <Spinner className="size-3" /> : null}{loading ? "Loading" : state}</Badge></div></CardHeader><CardContent className="divide-y"><DetailRow label="Provider" value={status?.provider ?? "-"} /><DetailRow label="Tunnel ID" value={<CopyValue value={status?.metadata?.id ?? status?.id ?? config.id ?? "-"} />} /><DetailRow label="Started" value={status?.started_at ? formatDate(status.started_at) : "-"} /><DetailRow label="Creator" value={status?.metadata?.creator ?? "-"} /><DetailRow label="Workspaces" value={<CopyList values={status?.metadata?.workspace_ids} />} /><DetailRow label="Organizations" value={<CopyList values={status?.metadata?.organization_ids} />} /><DetailRow label="Control plane" value={<CopyValue value={status?.control_plane_base_url ?? config.control_plane_base_url ?? "Default"} />} /><DetailRow label="Admin" value={status?.admin_key_configured ? `Configured · ${formatAdminScope(status.admin_scope)}` : "Not configured"} /></CardContent>{status?.last_error || status?.metadata_error ? <CardFooter><div className="w-full break-words rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{status.last_error || `Tunnel metadata unavailable: ${status.metadata_error}`}</div></CardFooter> : null}<CardFooter className="justify-end border-t"><Button disabled={busy || loading || !config.enabled} variant="outline" onClick={onToggle}>{active ? "Stop tunnel" : "Start tunnel"}</Button></CardFooter></Card> }
function ConfigField({ label, description, children }: { label: string; description: string; children: ReactNode }) { return <Field><FieldLabel>{label}</FieldLabel>{children}<FieldDescription>{description}</FieldDescription></Field> }
function CopyValue({ value }: { value: string }) { return <div className="flex min-w-0 items-start gap-1"><span className="min-w-0 flex-1 break-all font-mono text-sm font-normal">{value}</span>{value !== "-" && value !== "Default" ? <CopyButton value={value} /> : null}</div> }
function CopyList({ values }: { values?: string[] }) { return values?.length ? <div className="space-y-1">{values.map((value) => <CopyValue key={value} value={value} />)}</div> : "-" }
function runtimeConfig(config: TunnelConfig): TunnelConfig { return { enabled: config.enabled, id: config.id, api_key: config.api_key, control_plane_base_url: config.control_plane_base_url, organization_id: config.organization_id } }
function adminRequest(key: string, scope: AdminScopeKind, id: string): TunnelAdminKeyRequest { const request: TunnelAdminKeyRequest = { admin_key: key.trim() || undefined }; if (scope === "organization") request.organization_id = id.trim(); else if (scope === "workspace") request.workspace_id = id.trim(); else request.tenant_id = id.trim(); return request }
function applyAdminStatus(value: TunnelAdminKeyStatus, setConfigured: (value: boolean) => void, setScope: (value: AdminScopeKind) => void, setScopeID: (value: string) => void) { setConfigured(value.configured); const [kind, id] = adminScopeValue(value.scope); if (kind) setScope(kind); setScopeID(id) }
function adminScopeValue(scope?: TunnelAdminScope): [AdminScopeKind | undefined, string] { if (scope?.organization_id) return ["organization", scope.organization_id]; if (scope?.workspace_id) return ["workspace", scope.workspace_id]; if (scope?.tenant_id) return ["tenant", scope.tenant_id]; return [undefined, ""] }
function formatAdminScope(scope?: TunnelAdminScope) { const [kind, id] = adminScopeValue(scope); return kind && id ? `${kind}:${id}` : "scope unavailable" }
function adminResultMessage(message: string, result: TunnelAdminKeyStatus) { return result.tunnels === undefined ? `${message}.` : `${message} · ${result.tunnels} tunnel${result.tunnels === 1 ? "" : "s"} accessible.` }
function scopeLabel(scope: AdminScopeKind) { return scope[0].toUpperCase() + scope.slice(1) }
function scopePlaceholder(scope: AdminScopeKind) { return scope === "organization" ? "org_..." : scope === "workspace" ? "Workspace ID" : "Tenant ID" }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString() }
function errorText(value: unknown) { return value instanceof Error ? value.message : String(value) }
