import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { App } from "@/App"
import { ThemeProvider } from "@/components/theme-provider"
import { adminDocumentTitle, navItems } from "@/lib/admin-navigation"
import { adminToken } from "@/lib/api"

const config = {
  server: { port: 37421, expose: { mode: "none", interfaces: [] }, allow_insecure_http: false },
  admin: { enabled: true, port: 37422 },
  auth: { mcp_enabled: true, admin_enabled: true, mcp_token_configured: true, admin_token_configured: true },
  permissions: { allow_dirs: [] },
  shell: { path: [] },
  features: { ponytail: { enabled: true }, caveman: { enabled: true } },
}
const presets = { current: "default", presets: [{ name: "default", description: "Default", server: config.server, admin: config.admin, mcp_auth_enabled: true, admin_auth_enabled: true, tunnel_enabled: false, features: config.features }] }
const tunnel = { provider: "openai", enabled: false, running: false, ready: false }

describe("admin app runtime smoke", () => {
  beforeEach(() => {
    adminToken.set("test-admin-token")
    vi.stubGlobal("fetch", vi.fn(mockFetch))
    document.title = ""
  })

  afterEach(() => {
    adminToken.clear()
    vi.unstubAllGlobals()
  })

  it("mounts the authenticated shell and every main page with the correct document title", async () => {
    const user = userEvent.setup()
    renderAdminApp()

    await waitFor(() => expect(document.title).toBe(adminDocumentTitle("Overview")))
    expect(await screen.findByText("Active listeners and configuration preset.")).toBeInTheDocument()

    const pageSmokeText: Record<string, string> = {
      workspaces: "Register workspace",
      tools: "Inspect every tool exposed by the local runtime and enabled upstream servers, including schemas and behavioral hints.",
      servers: "Add MCP server",
      tunnel: "OpenAI Secure MCP Tunnel",
      activity: "Live MCP requests, tool calls, and runtime lifecycle events. Open any event to inspect its complete metadata.",
      settings: "Config preset",
    }
    for (const item of navItems.slice(1)) {
      await user.click(screen.getByRole("button", { name: item.title }))
      await waitFor(() => expect(document.title).toBe(adminDocumentTitle(item.title)))
      expect((await screen.findAllByText(pageSmokeText[item.id])).length).toBeGreaterThan(0)
    }
  })

  it("uses a login title when admin authentication rejects the current token", async () => {
    vi.stubGlobal("fetch", vi.fn(async (input: RequestInfo | URL) => {
      if (requestPath(input) === "/api/health") return new Response("unauthorized", { status: 401 })
      return mockFetch(input)
    }))
    renderAdminApp()
    expect(await screen.findByText("Enter the admin token generated by the CLI.")).toBeInTheDocument()
    await waitFor(() => expect(document.title).toBe(adminDocumentTitle("Login")))
  })

  it("uses a connecting title while the initial health check is pending", async () => {
    let resolveHealth: ((response: Response) => void) | undefined
    vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => {
      if (requestPath(input) === "/api/health") return new Promise<Response>((resolve) => { resolveHealth = resolve })
      return mockFetch(input)
    }))
    renderAdminApp()
    expect(await screen.findByText("Connecting to admin API...")).toBeInTheDocument()
    await waitFor(() => expect(document.title).toBe(adminDocumentTitle("Connecting")))
    resolveHealth?.(json({ ok: true, auth_enabled: true }))
    await waitFor(() => expect(document.title).toBe(adminDocumentTitle("Overview")))
  })
})

function renderAdminApp() { return render(<ThemeProvider><App /></ThemeProvider>) }

async function mockFetch(input: RequestInfo | URL): Promise<Response> {
  const path = requestPath(input)
  if (path === "/api/health") return json({ ok: true, auth_enabled: true })
  if (path === "/api/workspaces") return json([])
  if (path === "/api/tools") return json([])
  if (path === "/api/upstream") return json([])
  if (path === "/api/tunnel") return json(tunnel)
  if (path === "/api/tunnel/config") return json({ enabled: false })
  if (path === "/api/config") return json(config)
  if (path === "/api/config/presets") return json(presets)
  if (path === "/api/network/interfaces") return json([])
  if (path === "/api/activity/stream?history=100") return activityStream()
  throw new Error(`Unhandled test request: ${path}`)
}

function requestPath(input: RequestInfo | URL) {
  const raw = input instanceof Request ? input.url : String(input)
  const url = new URL(raw, "http://localhost")
  return `${url.pathname}${url.search}`
}

function json(value: unknown) { return new Response(JSON.stringify(value), { status: 200, headers: { "Content-Type": "application/json" } }) }

function activityStream() {
  const encoder = new TextEncoder()
  const body = new ReadableStream({ start(controller) { controller.enqueue(encoder.encode('event: ready\ndata: {"latest_sequence":0}\n\n')); controller.close() } })
  return new Response(body, { status: 200, headers: { "Content-Type": "text/event-stream" } })
}
