import { LogOut } from "lucide-react"
import { ThemeMenu } from "@/components/theme-menu"
import { Button } from "@/components/ui/button"
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarRail, SidebarSeparator, useSidebar } from "@/components/ui/sidebar"
import { navItems } from "@/lib/admin-navigation"

export function AppSidebar({ page, onPageChange, authRequired, onSignOut }: { page: string; onPageChange: (page: string) => void; authRequired: boolean; onSignOut: () => void }) {
  const { isMobile, setOpenMobile } = useSidebar()
  function navigate(next: string) { onPageChange(next); if (isMobile) setOpenMobile(false) }
  return <Sidebar collapsible="icon"><SidebarHeader className="p-3"><div className="flex items-center gap-2 overflow-hidden rounded-md px-1 py-1"><div className="flex size-7 shrink-0 items-center justify-center rounded-md bg-primary text-xs font-semibold text-primary-foreground">CM</div><div className="min-w-0 group-data-[collapsible=icon]:hidden"><div className="truncate text-sm font-semibold">chatgpt-mcp</div><div className="truncate text-[11px] text-muted-foreground">Admin dashboard</div></div></div></SidebarHeader><SidebarSeparator /><SidebarContent><SidebarGroup><SidebarGroupLabel>Runtime</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{navItems.map((item) => <SidebarMenuItem key={item.id}><SidebarMenuButton isActive={page === item.id} tooltip={item.title} onClick={() => navigate(item.id)}><item.icon /><span>{item.title}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarSeparator /><SidebarFooter><div className="flex items-center justify-between gap-1 group-data-[collapsible=icon]:flex-col"><div className="flex min-w-0 items-center gap-2 px-2 group-data-[collapsible=icon]:px-0"><span className="size-2 shrink-0 rounded-full bg-emerald-500" /><span className="truncate text-xs text-muted-foreground group-data-[collapsible=icon]:hidden">Admin connected</span></div><div className="flex items-center"><ThemeMenu />{authRequired ? <Button aria-label="Sign out" size="icon-sm" variant="ghost" onClick={onSignOut}><LogOut /></Button> : null}</div></div></SidebarFooter><SidebarRail /></Sidebar>
}
