import { LogOut } from "lucide-react"
import { ThemeMenu } from "@/components/theme-menu"
import { Button } from "@/components/ui/button"
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarRail, SidebarSeparator, useSidebar } from "@/components/ui/sidebar"
import { navItems } from "@/lib/admin-navigation"

export function AppSidebar({ page, onPageChange, authRequired, onSignOut }: { page: string; onPageChange: (page: string) => void; authRequired: boolean; onSignOut: () => void }) {
  const { isMobile, setOpenMobile } = useSidebar()
  function navigate(next: string) { onPageChange(next); if (isMobile) setOpenMobile(false) }
  const roots = navItems.filter((item) => !item.parent)
  return <Sidebar collapsible="icon"><SidebarHeader className="p-3"><div className="flex items-center gap-2 overflow-hidden rounded-md px-1 py-1"><div className="flex size-7 shrink-0 items-center justify-center rounded-md bg-primary text-xs font-semibold text-primary-foreground">CM</div><div className="min-w-0 group-data-[collapsible=icon]:hidden"><div className="truncate text-sm font-semibold">chatgpt-mcp</div><div className="truncate text-[11px] text-muted-foreground">Admin dashboard</div></div></div></SidebarHeader><SidebarSeparator /><SidebarContent><SidebarGroup><SidebarGroupLabel>Runtime</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{roots.map((item) => { const children = navItems.filter((child) => child.parent === item.id); const active = page === item.id || children.some((child) => child.id === page); return <SidebarMenuItem key={item.id}><SidebarMenuButton asChild isActive={active} tooltip={item.title}><a href={item.path} onClick={(event) => { if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; event.preventDefault(); navigate(item.id) }}><item.icon /><span>{item.title}</span></a></SidebarMenuButton>{children.length ? <SidebarMenuSub>{children.map((child) => <SidebarMenuSubItem key={child.id}><SidebarMenuSubButton asChild isActive={page === child.id}><a href={child.path} onClick={(event) => { if (event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return; event.preventDefault(); navigate(child.id) }}><child.icon /><span>{child.title}</span></a></SidebarMenuSubButton></SidebarMenuSubItem>)}</SidebarMenuSub> : null}</SidebarMenuItem> })}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarSeparator /><SidebarFooter><div className="flex items-center justify-between gap-1 group-data-[collapsible=icon]:flex-col"><div className="flex min-w-0 items-center gap-2 px-2 group-data-[collapsible=icon]:px-0"><span className="size-2 shrink-0 rounded-full bg-emerald-500" /><span className="truncate text-xs text-muted-foreground group-data-[collapsible=icon]:hidden">Admin connected</span></div><div className="flex items-center"><ThemeMenu />{authRequired ? <Button aria-label="Sign out" size="icon-sm" variant="ghost" onClick={onSignOut}><LogOut /></Button> : null}</div></div></SidebarFooter><SidebarRail /></Sidebar>
}
